### ISSUE TITLE
Violation noticed while debugging other module

### ISSUE THREAD

**Issue by BKeyport** [MMRIZE/MMM-CalendarExt3Agenda#17]
I keep getting this on startup cycle in the mirror. 

"[Violation] 'setTimeout' handler took 136ms" reports line 96.

**Comment by eouia** [comment]
I cannot understand what you said. Can you explain more? What is the issue?

**Comment by eouia** [comment]
That message happens when the routine inside of `setTimeout()` takes some noticeable time.  Time-interruption of JS could make some blocks in the process; so when some routine takes time, the message would be spit out.
Anyway, the message itself is not so scary thing, unlike its `Violation` meaning. So, you can just ignore it unless it makes `error` or malfunction.
Or you can improve my code more efficiently. Always welcome PR

**Comment by BKeyport** [comment]
Thanks for the explanation.
