### ISSUE TITLE
Issue synchronising repeatable events?

### ISSUE THREAD

**Issue by szech** [MMRIZE/MMM-CalendarExt3Agenda#64]
There seems to be a bug when editing or rescheduling repeatable events from Google.

- I made a repeatable event. This appeared as expected in the agenda widget.
- I changed the date of one of the events in Google ("This event only"). This did not update as expected in the agenda widget and still appears with the old date.
- I also changed the name of one of the repeatable events ("This event only"), and that did not update as expected either.

It would be great if anyone can replicate, or investigate.
Thanks for agenda widget, it's great having it on my mirror :)

=======

I have my widget setup to pull from Google calendar.

New events are showing up, so i don't believe there is any issue getting the calendar info.
Deleting and rescheduling regular events is also fine.

**Comment by eouia** [comment]
Could you provide an example ics URL?

**Comment by eouia** [comment]
This module gets the data from the default calendar module(or equivalent), But the default calendar module cannot parse that kind of data properly.

![image](https://github.com/user-attachments/assets/72e0c551-f762-4501-b008-e688e657deea)

I made two kinds of repeated events ("Every Thursday" - Fullday events and "Repeated Except" - momentary daily events), then each one specific event changed title and time, `(*)` mark is appended to be noticeable.

But, the default calendar cannot handle Fullday type event. It doesn't show `(*) Every Thursday` on date 14. Sep. So that's why CX3A also cannot display that event. That is not the fault of this module.


<img width="631" alt="image" src="https://github.com/user-attachments/assets/debbcb6d-9171-42d1-8b67-5b162cb06b5f">

So, report the symptom, "The default calendar cannot handle a modified event from repeated ones" to the MagicMirror's maintainers. (https://github.com/MagicMirrorOrg/MagicMirror/issues) Or the forum (https://forum.magicmirror.builders)

**Comment by szech** [comment]
Thanks for taking the time to investigate, I appreciate it
